### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by cxwya** [aiming-pro/verte-vue3#2]
这个页面使用组件时，报这个错误
verte.esm.js:731  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'backgroundImage')
    at Proxy.initGradient (verte.esm.js:731:25)
    at Proxy.gradient (verte.esm.js:682:12)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at job (runtime-core.esm-bundler.js:1756:9)
    at flushPreFlushCbs (runtime-core.esm-bundler.js:304:7)
    at updateComponentPreRender (runtime-core.esm-bundler.js:5832:5)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5750:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)

**Comment by jf908** [comment]
Fixed in 1.0.2
